baseimage:
  docker:
    image_name: nlevel/baseimage
    container_name: baseimage
    push_repo: nlevel/baseimage
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/baseimage
      glr: glr.markjeee.com/nlevel/baseimage

baseruby:
  docker:
    image_name: nlevel/baseruby
    container_name: baseruby
    bash: su -l rubydev
    push_repo: nlevel/baseruby
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/baseruby
      glr: glr.markjeee.com/nlevel/baseruby

  rubydev24:
    docker:
      image_name: nlevel/rubydev24
      container_name: rubydev24
      bash: su -l rubydev
      push_repo: nlevel/rubydev24
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev24
        glr: glr.markjeee.com/nlevel/rubydev24

  rubydev23:
    docker:
      image_name: nlevel/rubydev23
      container_name: rubydev23
      bash: su -l rubydev
      push_repo: nlevel/rubydev23
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev23
        glr: glr.markjeee.com/nlevel/rubydev23

squidy:
  docker:
    image_name: nlevel/squidy
    container_name: squidy
    push_repo: nlevel/squidy
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/squidy
      glr: glr.markjeee.com/nlevel/squidy
  var: $thomas_root/var/squidy
  port: 14002
  listen:
    - 127.0.0.1
    - 10.100.0.1
