baseimage:
  docker:
    image_name: nlevel/baseimage
    container_name: baseimage
    push_repo: nlevel/baseimage
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/baseimage
      glr: glr.markjeee.com/nlevel/baseimage

baseruby:
  docker:
    image_name: nlevel/baseruby
    container_name: baseruby
    bash: su -l rubydev
    push_repo: nlevel/baseruby
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/baseruby
      glr: glr.markjeee.com/nlevel/baseruby

  rubydev24:
    docker:
      image_name: nlevel/rubydev24
      container_name: rubydev24
      bash: su -l rubydev
      push_repo: nlevel/rubydev24
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev24
        glr: glr.markjeee.com/nlevel/rubydev24

  rubydev23:
    docker:
      image_name: nlevel/rubydev23
      container_name: rubydev23
      bash: su -l rubydev
      push_repo: nlevel/rubydev23
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev23
        glr: glr.markjeee.com/nlevel/rubydev23

squidy:
  docker:
    image_name: nlevel/squidy
    container_name: squidy
    push_repo: nlevel/squidy
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/squidy
      glr: glr.markjeee.com/nlevel/squidy
  docker_run:
    var: $thomas_root/var/squidy
    port: 14002
    listen:
      - 127.0.0.1
      - 10.100.0.1

konsol:
  docker:
    image_name: nlevel/konsol
    container_name: konsol
    push_repo: nlevel/konsol
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/konsol
      glr: glr.markjeee.com/nlevel/konsol
  docker_run:
    domain: cluster.dev
    node: vmhost
    advertise: 10.100.0.1
    var: $thomas_root/var/konsol
    config: $thomas_root/konsol/config
    client_port: 8500
    dns_port: 8600
    rpc_port: 8400
    cluster_lan_port: 8301
    cluster_wan_port: 8302
    cluster_rpc_port: 8300
    listen:
      - 127.0.0.1
      - 10.100.0.1

reddys:
  docker:
    image_name: nlevel/reddys
    container_name: reddys
    push_repo: nlevel/reddys
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/reddys
      glr: glr.markjeee.com/nlevel/reddys
  docker_run:
    var: $thomas_root/var/reddys
    port: 14006
    durable_port: 14007
