baseimage:
  docker:
    image_name: thomas.baseimage
    push_repo: nlevel/baseimage
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/baseimage
      glr: glr.markjeee.com/nlevel/baseimage

baseruby:
  docker:
    image_name: thomas.baseruby
    push_repo: nlevel/baseruby
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/baseruby
      glr: glr.markjeee.com/nlevel/baseruby
    bash: su -l rubydev

  rubydev25:
    docker:
      image_name: thomas.rubydev25
      push_repo: nlevel/rubydev25
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev25
        glr: glr.markjeee.com/nlevel/rubydev25
      bash: su -l rubydev

  rubydev24:
    docker:
      image_name: thomas.rubydev24
      push_repo: nlevel/rubydev24
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev24
        glr: glr.markjeee.com/nlevel/rubydev24
      bash: su -l rubydev

  rubydev23:
    docker:
      image_name: thomas.rubydev23
      push_repo: nlevel/rubydev23
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev23
        glr: glr.markjeee.com/nlevel/rubydev23
      bash: su -l rubydev

  rubydev22:
    docker:
      image_name: thomas.rubydev22
      push_repo: nlevel/rubydev22
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev22
        glr: glr.markjeee.com/nlevel/rubydev22
      bash: su -l rubydev

  rubydev19:
    docker:
      image_name: thomas.rubydev19
      push_repo: nlevel/rubydev19
      push_mirrors:
        gcr: asia.gcr.io/nlevel-164003/nlevel/rubydev19
        glr: glr.markjeee.com/nlevel/rubydev19
      bash: su -l rubydev

squidy:
  docker:
    image_name: thomas.squidy
    push_repo: nlevel/squidy
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/squidy
      glr: glr.markjeee.com/nlevel/squidy
  docker_run:
    var: $thomas_root/var/squidy
    port: 14002
    listen:
      - 127.0.0.1
      - 10.100.0.1

konsol:
  docker:
    image_name: thomas.konsol
    push_repo: nlevel/konsol
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/konsol
      glr: glr.markjeee.com/nlevel/konsol
  docker_run:
    domain: cluster.devbox
    node: vmhost
    advertise: 10.100.0.1
    var: $thomas_root/var/konsol
    config: $thomas_root/konsol/config
    client_port: 8500
    dns_port: 8600
    rpc_port: 8400
    cluster_lan_port: 8301
    cluster_wan_port: 8302
    cluster_rpc_port: 8300
    listen:
      - 127.0.0.1
      - 10.100.0.1

reddys:
  docker:
    image_name: thomas.reddys
    push_repo: nlevel/reddys
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/reddys
      glr: glr.markjeee.com/nlevel/reddys
  docker_run:
    var: $thomas_root/var/reddys
    port: 14006
    durable_port: 14007

gitti:
  docker:
    image_name: thomas.gitti
    push_repo: nlevel/gitti
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/gitti
      glr: glr.markjeee.com/nlevel/gitti
  docker_run:
    var: $thomas_root/var/gitti
    port: 14001
    listen:
      - 127.0.0.1
      - 10.100.0.1
    private_key: '~/.ssh/some_private_key'
    git_server: 'git@some_git_server'
    repos:

php5-fpm-mcrypt:
  docker:
    image_name: thomas.php5-fpm-mcrypt
    push_repo: nlevel/php
    push_tag: 5-fpm-mcrypt
    push_mirrors:
      gcr: asia.gcr.io/nlevel-164003/nlevel/php
      glr: glr.markjeee.com/nlevel/php
